quamotion/madb

SharpAdbClient.Extensions/Device.cs, SharpAdbClient.Tests/DummyTcpSocket.cs, SharpAdbClient.Tests/SocketBasedTests.cs, SharpAdbClient.Tests/TracingAdbSocket.cs, SharpAdbClient/AdbClient.cs, SharpAdbClient/AdbCommandLineClient.cs, SharpAdbClient/AdbServer.cs, SharpAdbClient/AdbSocket.cs, SharpAdbClient/Factories.cs, SharpAdbClient/ITcpSocket.cs, SharpAdbClient/SharpAdbClient.csproj, SharpAdbClient/TcpSocket.cs, SharpAdbClient/packages.config
There was a hard-coded check for an `adb.exe` path, but on Linux that's just `adb`.
=> Support launching the adb client on Linux-based operating Systems.

SharpAdbClient/DeviceMonitor.cs
If a ThreadAbortException is caught in the DeviceMonitorLoop, and it was triggered by the Dispose method, ignore it. Else, log it.
=> Fix: DeviceMonitor.Dispose() does an abort of the background thread.

SharpAdbClient/DeviceMonitor.cs
DeviceMonitor: Shut down the device monitor task before closing the socket (the task uses the socket).
=> Fix ObjectDisposedException in DeviceMonitor.Dispose

SharpAdbClient.Tests/DummyAdbClient.cs, SharpAdbClient.Tests/ForwardDataTests.cs, SharpAdbClient.Tests/ForwardSpecTests.cs, SharpAdbClient.Tests/SharpAdbClient.Tests.csproj, SharpAdbClient/AdbClient.cs, SharpAdbClient/DeviceCommands/AndroidProcess.cs, SharpAdbClient/ForwardData.cs, SharpAdbClient/ForwardProtocol.cs, SharpAdbClient/ForwardSpec.cs, SharpAdbClient/IAdbClient.cs, SharpAdbClient/SharpAdbClient.csproj
Supports parsing the forward specifications used by adb, such as tcp:80 or localabstract:/tmp/1234
=> Add ForwardSpec class

SharpAdbClient/AdbClient.cs, SharpAdbClient/AdbSocket.cs
This should also reduce the CPU-Use on other function that use `Read` or `ReadAsync`.
=> fix CPU-Use on GetFrameBufferAsync #40

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceData.cs
Hi @Viper2k4,
This PR should help with #42: perhaps as a coincidence, I just found out that I got an exception when an emulator is connected to adb, like this:
```
>adb.exe devices
List of devices attached
emulator-5586   host
```
I've fixed that, added a unit test for the case and also made sure the `CreateFromAdbData` method includes the invalid data if an exception is thrown.
Can you let me know whether this fixes the issue for you, or if the issue still reproduces, can you amend #42 and attach the updated error message + stack trace?
Thanks!
PS: I'm looking to do a new release on NuGet soon, after I've completed #43 .
@bartsaintgermain Can you review and approve?
=> Add support for emulator devices

SharpAdbClient.Benchmarks/App.config, SharpAdbClient.Benchmarks/FileUploadBufferSize.cs, SharpAdbClient.Benchmarks/Program.cs, SharpAdbClient.Benchmarks/Properties/AssemblyInfo.cs, SharpAdbClient.Benchmarks/SharpAdbClient.Benchmarks.csproj, SharpAdbClient.Benchmarks/packages.config, SharpAdbClient.Tests/DummyAdbClient.cs, SharpAdbClient.Tests/DummyAdbSocket.cs, SharpAdbClient.Tests/FramebufferTests.cs, SharpAdbClient.Tests/SharpAdbClient.Tests.csproj, SharpAdbClient.sln, SharpAdbClient/AdbClient.cs, SharpAdbClient/AdbSocket.cs, SharpAdbClient/Framebuffer.cs, SharpAdbClient/IAdbClient.cs, SharpAdbClient/IAdbSocket.cs, SharpAdbClient/Log.cs, SharpAdbClient/SharpAdbClient.csproj, SharpAdbClient/SyncService.cs
Hi @Viper2k4,
I finally got round to having a look at the framebuffer performance you're reported in #40 .
Here's what I found so far:
* In the Visual Studio screenshot you've attached, you can see there's a lot of garbage collection activity going on (the triangles in the performance debugger)
* Garbage collection happens typically when you create new objects and then throw them away. In SharpAdbClient, memory allocation happened in two different places:
- When you call `GetFramebuffer`, a new `byte[]` array is created which holds the raw framebuffer data. This can be up to several megabytes of memory, which is allocated every time you call `GetFramebuffer`
- The `AdbSocket` class wasn't (and still isn't) very good at managing memory either - when retrieving data, it allocated temporary …
=> Improve Framebuffer performance

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceCommands/DeviceExtensions.cs, SharpAdbClient/DeviceCommands/PackageManager.cs, SharpAdbClient/DeviceData.cs, appveyor.yml
- Allow dependency injection of the IAdbClient class in the SyncServiceFactory class
- Add support for the 'usb' property in the device list, which appears on Linux
- Update appveyor.yml file; remove download of the .NET Core SDK; it is already available on the build servers
/cc @bartsaintgermain
=> Enhance dependency injection, enable running on Linux

SharpAdbClient.Tests/DeviceCommands/AndroidProcessTests.cs, SharpAdbClient.Tests/DeviceCommands/DeviceExtensionsTests.cs, SharpAdbClient/DeviceCommands/AndroidProcess.cs, SharpAdbClient/DeviceCommands/DeviceExtensions.cs, SharpAdbClient/Receivers/ProcessOutputReceiver.cs
- Fix issue where only a couple of processes are returned
- Fix issue where the process name would be truncated; prefix the {pid}/stat output with the {pid}/cmdline output
=> ListProcesses improvements

SharpAdbClient/AdbClient.cs, SharpAdbClient/IAdbClient.cs, SharpAdbClient/IAdbClient.xml, SharpAdbClient/Logs/AndroidLogEntry.cs, SharpAdbClient/Logs/LogReader.cs, SharpAdbClient/Logs/Priority.cs, SharpAdbClient/SharpAdbClient.csproj
* You can now pass a `CancellationToken` to the `RunLogService` method, which allows you to stop the logcat client
* You can now call `.ToString()` on logcat messages and receive a message in the `adb logcat` output format.
=> Logcat client improvements

SharpAdbClient.Tests/AdbClientTests.cs, SharpAdbClient.Tests/DummyAdbClient.cs, SharpAdbClient/AdbClient.cs, SharpAdbClient/Framebuffer.cs, SharpAdbClient/SharpAdbClient.csproj, SharpAdbClient/SharpAdbClient.project.json, SharpAdbClient/project.json
- Make Framebuffer implement IDisposable, and allow pooling of the byte array used by the framebuffer to prevent unnecessary allocations/deallocations
- Make sure the AdbSocket is disposed of in RefreshAsync
/cc @bartsaintgermain
=> Fix memory leaks in GetFrameBufferAsync

SharpAdbClient.Tests/AdbClientTests.cs, SharpAdbClient.Tests/DummyAdbClient.cs, SharpAdbClient.Tests/LoggerTests.cs, SharpAdbClient/AdbClient.cs, SharpAdbClient/Framebuffer.cs, SharpAdbClient/IAdbClient.cs, SharpAdbClient/IAdbClient.xml, SharpAdbClient/Logs/LogReader.cs, SharpAdbClient/SharpAdbClient.csproj, SharpAdbClient/SharpAdbClient.project.json, SharpAdbClient/project.json
Currently, RunLogService would check whether a cancellation was requested every time a message is received. However, if there is a large delay between two subsequent messages (say, multiple seconds or even minutes), the cancellation would never be processed.
This PR makes sure that the network I/O can also be cancelled, so the cancellation works correctly even if the loop is stuck waiting for network I/O for a long period of time.
/cc @bartsaintgermain
=> Make the RunLogServiceAsync method truly async

SharpAdbClient.Tests/DeviceCommands/DeviceExtensionsTests.cs, SharpAdbClient/DeviceCommands/DeviceExtensions.cs
Android 7 and above uses toybox, which outputs multiple items on one line. Pass the `-1` flag to make sure each item gets its own line.
The `-1` flag causes problems on Android < 7, so check for that, too.
=> Fix listing processes on Android 7 and above

SharpAdbClient.Tests/LoggerTests.cs, SharpAdbClient/Logs/LogReader.cs, SharpAdbClient/Logs/ShellStream.cs
- Support reading 0 bytes of data in the ShellStream
- Improve the error message when the header size is unreasonably large.
=> Minor bug fixes in the logging service client

SharpAdbClient.Tests/PackageManagerTests.cs, SharpAdbClient/DeviceCommands/PackageManager.cs
Now using [Google's reference](https://github.com/android/platform_system_core/blob/master/adb/commandline.cpp#L2063) for the default temporary installation directory.
This also might fix #75
=> Update Temporary Installation Directory

SharpAdbClient.Tests/PackageManagerReceiverTests.cs, SharpAdbClient/DeviceCommands/PackageManager.cs, SharpAdbClient/DeviceCommands/PackageManagerReceiver.cs, SharpAdbClient/SharpAdbClient.csproj, appveyor.yml
With O it appears there is a base64 checksum in the directory of third party packages.
`
package:/data/app/com.google.android.apps.plus-qQaDuXCpNqJuQSbIS6OxGA==/base.apk=com.google.android.apps.plus`
This PR accomodates for that
Fixes #79 
/cc @bartsaintgermain
=> Fix issue with parsing list of installed packages on Android O.

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceData.cs
Devices in recover mode do not provide a device model, but have device strings like this:
```
ZY3222LBDC recovery usb:337641472X product:omni_cedric device:cedric
```
This PR makes the product and model optional in the device string.
=> Make product, model optional in the device data string.

SharpAdbClient.Tests/DeviceCommands/DeviceExtensionsTests.cs, SharpAdbClient/DeviceCommands/VersionInfoReceiver.cs
VersionInfoReceiver: Support getting the versionCode even when targetSdk is missing.
=> Fix VersionInfoReceiver

SharpAdbClient.Tests/PackageManagerTests.cs, SharpAdbClient.Tests/SharpAdbClient.Tests.csproj, SharpAdbClient.Tests/VersionInfoReceiverTests.cs, SharpAdbClient.Tests/gapps.txt, SharpAdbClient/DeviceCommands/VersionInfoReceiver.cs
If preinstalled apps are updated, they appear in both the `Packages:` and `Hidden system packages:` sections of the `dumpsys package` output.
This PR makes sure that we only look at the `Packages:` section when getting the version information.
=> Fix GetVersionInfo for updated, pre-installed apps

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient.Tests/SharpAdbClient.Tests.csproj, SharpAdbClient/DeviceData.cs, appveyor.yml
The NuGet package references used by the unit test project were outdated, this updates them.
Also adds further unit tests for the transport_id field.
=> Update unit tests

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceData.cs
Fix the new message sent by ADB when a new device is connected to PC.
Now, on connection, ADB send two messages in this sequence:
"connecting" "device"
=> Fix the new message received on connection

SharpAdbClient/SharpAdbClient.csproj
This should make debugging SharpAdbClient easier for our users. See https://github.com/dotnet/sourcelink for more information about SourceLink.
=> Enable SourceLink support

README.md
PackageManager is used instead of ApplicationManager for managing applications.
=> Fixed a class name in README

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceData.cs, SharpAdbClient/DeviceState.cs
On recent adb versions devices can be in the authorizing state. This PR accounts for this.
=> Add support for authorizing state

SharpAdbClient.Tests/DeviceDataTests.cs, SharpAdbClient/DeviceData.cs
adb devices returns in some cases the following message:
009d1cd696d5194a        no permissions (user in plugdev group; are your udev rules wrong?); see [http://developer.android.com/tools/device.html
Currently this raised an exception, this PR accounts for this.
=> account for a message after no Permissions

SharpAdbClient.Tests/AdbClientTests.cs, SharpAdbClient.Tests/AdbSocketTests.cs, SharpAdbClient/AdbClient.cs
List Devices is failing when Android Studio is running a newer ADB server version. 
According to the tips for #147, I've removed the '\n' char and fixed related tests.
I hope this PR could help you.
=> Fixed: #147 #149 'unknown host service' error.

SharpAdbClient/SharpAdbClient.csproj
For those stuck on legacy systems. .NET 4.6.1 is the oldest version of NetFx which supports `netstandard2.0`, so this is as low as we can go. Closes #180
=> Target .NET 4.6.1

SharpAdbClient.Tests/AdbClientTests.cs, SharpAdbClient.Tests/AdbServerTests.cs, SharpAdbClient.Tests/ConsoleOutputReceiverTests.cs, SharpAdbClient.Tests/DummyAdbCommandLineClient.cs
Ignore line-ending differences (`\r\n` vs `\r`) and account for the adb executable name differences (`adb` vs `adb.exe`)
=> Make unit tests cross-platform

SharpAdbClient.Tests/ShellStreamTests.cs, SharpAdbClient/Logs/ShellStream.cs
We encourage asynchronously executing a command on the device using `AdbClient.ExecuteRemoteCommandAsync`.
However, this will then use a `ShellStream` which only supports synchronous reading data off the stream.
Additionally, to support cancellation, `AdbClient.ExecuteRemoteCommandAsync` will invoke `cancellationToken.Register(() => socket.Dispose())`.
However, on Unix, calling `socket.Dispose` will not unblock synchronous calls for current versions of .NET Core. (This is fixed in .NET 5.0). https://github.com/dotnet/corefx/pull/38804 has the details.
As a result, cancellation of `ExecuteRemoteCommandAsync` methods is effectively impossible.
This PR implements aynchronous methods in `ShellStream`, making the scenario work.
=> ShellStream: Add ReadAsync implementation

SharpAdbClient.Tests/DummyAdbClient.cs, SharpAdbClient/AdbClient.cs, SharpAdbClient/AdbClientExtensions.cs, SharpAdbClient/IAdbClient.cs
- Remove unused maxTimeToOutputResponse parameter
- Make sure CancellationToken is the last parameter
=> ExecuteRemoteCommandAsync: cleanup
